quarkus.http.port=8081
quarkus.smallrye-graphql.schema-selection=all
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_HOST}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.hibernate-orm.database.generation=update
quarkus.index-dependency.common.group-id=com.mineplex.service
quarkus.index-dependency.common.artifact-id=common

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*